[project]
name = 'Wormhole-Stabilization-Consortium'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.wormhole-management]
path = 'contracts/wormhole-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.wormhole-nft]
path = 'contracts/wormhole-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
